
rfoutlet: /var/www/rfoutlet
	sudo chown root.root /var/www/rfoutlet/codesend
	sudo chmod 4755 /var/www/rfoutlet/codesend

/var/www/rfoutlet:
	sudo git clone git://github.com/timleland/rfoutlet.git /var/www/rfoutlet

run:
	sudo /var/www/rfoutlet/RFSniffer

