

vim: /usr/bin/vim
zsh: /usr/bin/zsh
tmux: /usr/bin/tmux

xclip: /usr/bin/xclip
bc: /usr/bin/bc

/usr/bin/%:
	#sudo apt-get -y install $(@)

apache:
	sudo apt-get -y install apache2 php5 libapache2-mod-php5

mail: /etc/ssmtp/ssmtp.conf /usr/bin/mail

/etc/ssmtp/ssmtp.conf:
	sudo apt-get -y install ssmtp

/usr/bin/mail:
	sudo apt-get -y install mailutils



#apt-get -y install apache2 php5 libapache2-mod-php5

